### ISSUE TITLE
Inconsistency in id naming - resource_id, user_id, streamid

### ISSUE THREAD

**Issue by andreasmh** [projectcs13/sensor-cloud#132]
I propose that we change streamid to stream_id.

**Comment by nikokon** [comment]
I agree

**Comment by nikokon** [comment]
Currently It's streamid in the datapoint mapping. Where does this need to change? ES?

**Comment by iakovosk** [comment]
Also, the timestamp type should be changed to date from string

**Comment by nikokon** [comment]
I'll mark this as resolved for now...
