### ISSUE TITLE
exchange name and type

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#162]
I'm trying to figure out what the exchange name and type is in order to subscribe via rabbit mq. Is there a way of figuring this out?

**Comment by gabrieltholsgard** [comment]
A stream publish to the exchange <<"streams.id">>, so a stream with id "1" publish data to the exchange  <<"streams.1">>
For virtual streams it would be: <<"vstreams.id">>, so a virtual stream with id "2" publish data to the exchange <<"vstreams.2">>

**Comment by konstantino** [comment]
Hi Gabriel, thank you for responding. Yes, after doing a concat with 'streams.' it worked nicely. I will post the sample client I wrote in JAVA in the wiki as a reference for future users.

**Comment by konstantino** [comment]
One quick question. How does it work now with the predictive stream that you guys are creating? Is it vstrem and then the stream id of the original stream?

**Comment by steine** [comment]
Sad to say, but the predictions is not their own stream. Right now it is 
just generated and visualized.
