### ISSUE TITLE
live update and predictions problem

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#165]
seems like live update is still not working after enabling node-js. could use some help troubleshooting. Moreover, predictions do not work as well. Clicking the prediction button gives this error:

parsing "library(forecast)"
20
parse status=1, result=25bec98, type=20
This is forecast 4.8 

TYPEOF:16
LENGTH:8
parsing "V <- c()"
20
parse status=1, result=2d7a598, type=20
TYPEOF:0
LENGTH:25026648
parsing "A <- auto.arima(V)"
20
parse status=1, result=2d7a5f8, type=20
Error in ts(x) : 'ts' object must have one or more observations
Re_ClearerrConsole

 **\* caught segfault ***
address (nil), cause 'memory not mapped'

**Comment by andreasmh** [comment]
The prediction is giving an error because the stream you are trying to predict has no values. The current version in develop should not give an error though, it should return an empty prediction list, like this "{"predictions": []}".

**Comment by konstantino** [comment]
How many values are needed for a prediction? Also how do I debug live
updates? All that happens now is that live updates are missed.

**Comment by konstantino** [comment]
updating to the latest version I'm still having troubles with the live update. Moreover I receive this error message upon running nodejs:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'uglify-js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/opt/sensor-cloud/node_modules/socket.io/node_modules/socket.io-client/bin/builder.js:13:14)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

**Comment by krewie** [comment]
Hello Kosta, try running "npm install socket.io" and "npm install rabbit.js", you should have npm installed on your machine i believe, after the packages are installed run "node receive.js" again , let me know if it worked, i will create a better documentation for this in the wiki.

**Comment by konstantino** [comment]
Already have. What I've noticed is that when I run npm install these
modules are installed in a directory called node_modules in the same
directory where I've run the command. Anyhow the problem is still here. It
occurs when I start node js in the latest version of the sensor-cloud. It
did not occur in earlier versions.

On Wed, Nov 27, 2013 at 10:38 AM, Kristian Ionescu <notifications@github.com

**Comment by krewie** [comment]
the node_modules are the packages that are installed once you call npm install , these should be located in the javascripts folder, i have updated the start script to check and see if this folder exists (node_modules) and download the neccesary packages to the correct folder if not

**Comment by konstantino** [comment]
I see, so the problem starts because these files land in the wrong place.
I'll rectify this. So it should be javascripts/node_modules then right?

On Wed, Nov 27, 2013 at 11:14 AM, Kristian Ionescu <notifications@github.com

**Comment by krewie** [comment]
I believe so , if this is not the case we might be running different versions of nodejs and i'll have to check that out, could you run node --version in your terminal and paste the version number here

**Comment by konstantino** [comment]
v0.6.12 - it's the one that comes with ubuntu via apt-get

On Wed, Nov 27, 2013 at 11:21 AM, Kristian Ionescu <notifications@github.com

**Comment by konstantino** [comment]
So actually no. I still get the same problem but now the directory is different because I moved the scripts.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'uglify-js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/opt/sensor-cloud/javascripts/node_modules/socket.io/node_modules/socket.io-client/bin/builder.js:13:14)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

**Comment by konstantino** [comment]
I will follow this guide here to update to latest nodejs: https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#ubuntu-mint. I'll let you know how it goes.

**Comment by krewie** [comment]
Could you try this instead and run with "nodejs receive.js" instead of "node receive.js" ? ; https://github.com/projectcs13/sensor-cloud/wiki/Setup#install-nodejs

**Comment by konstantino** [comment]
Just updated to v0.10.22 and both node nodejs offer the same version - I
think it's even the same file symbolically linked. I haven't run yet the
system with the new new nodejs so give me a second to try this and I'll let
you know.

**Comment by konstantino** [comment]
Ok. After upgrading to the latest nodejs I get no errors/warnings at
startup. I'm gonna try the live update now and let you know.

**Comment by konstantino** [comment]
ok, still does not work. toggling the on/off button pushes an alert that says true and afterwards pushing new values into the system, they are not updated on the fly.

**Comment by krewie** [comment]
does nodejs say "info  - socket.io started" when running receive.js ?

**Comment by konstantino** [comment]
no it doesn't. not from what I can say in the console or the logs. Strangely enough that used to be the case before, prior to upgrading to v0.10.22. i would get this message but live update would still not work + I would get warnings.

**Comment by konstantino** [comment]
scratch this out. I do see this message now in the logs. so I do get the socket.io started message.

**Comment by nikokon** [comment]
good thing pointing out the pop-up (that should be removed, was put there for debugging reasons) 
Which version of the frontend are you running? it should be working... Everything's working fine here :/ 
The graph is working fine other than the live-update? does the console in the web browser display any errors?

**Comment by konstantino** [comment]
OK. Was able to get some more information on the logs. Here's what I get from the browser javascript console:

http://localhost:8080/socket.io/1/?ns=http://localhost:8080/streams.Avpy9e5SQhygbAuYMb9myg&t=1385557019187

**Comment by konstantino** [comment]
ok the problem is now fixed. the was a port forwarding problem since I was running this on a virtual machine but now its good.

**Comment by nikokon** [comment]
hmm.. if that prints in the console I guess it fails to load that resource. So either socket.io is not running (which I think it is, reading the above discussion) or the socket io is not served on http://localhost:8080. In the front-end there is a config file (config/config.yml) where you specify the base url to the API as well as the Node js server

**Comment by nikokon** [comment]
OH! great! BTW, is the Y-Axis in the graph still reverse? steine sent an image the other day but I couldn't recreate the problem

**Comment by konstantino** [comment]
actually me neither. I haven't been able to recreate it since. Must have
been a fluke.
