### ISSUE TITLE
datapoint post fails after the system runs for a while

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#170]
Maybe you guys have seen this issue before:

<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,
    {error,
        {badmatch,{error,handshake_receive_timed_out}},
        [{datapoints,process_post,2,[{file,"src/datapoints.erl"},{line,108}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,486}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]},
         {webmachine_mochiweb,loop,2,
             [{file,"src/webmachine_mochiweb.erl"},{line,74}]},
         {mochiweb_http,parse_headers,5,
             [{file,"src/mochiweb_http.erl"},{line,180}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></html>-XPOST -H Content-type: application/json -d {"value":"115.50"}

So essentially the HTTP POST for a particular stream just stopped working after a while with this error.

**Comment by andreasmh** [comment]
I think we located the problem, the pubsub connection was not being closed properly. A fix will be appearing in develop in a minute or two.

**Comment by andreasmh** [comment]
Just to clarify, the datapoints were still being entered to the system and elasticsearch, but the pub/sub system was timing out.
