### ISSUE TITLE
Poller only restarts 10 streams

### ISSUE THREAD

**Issue by andreasmh** [projectcs13/sensor-cloud#191]
Change query to this! Or something similar...
{"size":1000,"filter" : {"exists" : {"field" : "uri"}}}}}

**Comment by andreasmh** [comment]
Maybe something like this? I haven't found anything to get everything so adding a large size is the only solution I have so far.

And maybe search for polling instead of uri?
{"size":1000000,"filter": {"term": {"polling": true}}}

**Comment by gxlzlihao** [comment]
I have change the query string in my local branch, will upload it soon.

**Comment by gxlzlihao** [comment]
have pushed the latest code, please review it,

**Comment by andreasmh** [comment]
fixed #195
