### ISSUE TITLE
timestamp based data point retrieval

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#212]
is there an example on how that can be done, querying datapoints within a particular time interval?

**Comment by iakovosk** [comment]
Yes, it is explained in the documentation in datapoints.erl:

the POST range query should be structed as follows:
    curl -XPOST http://localhost:8000/streams/<stream_id>/data/_search -d '{
        "size" : 100,
        query:{
           "filtered" : {
               "query" : {
                  "term" : { "streamid" : Id }
              }, "filter" : {  "range" : {    "timestamp" : {"gte" : timestampFromValue,"lte" : timestampToValue}}}}
         },"sort" : [{"timestamp" : {"order" : "asc"}}]  }'

the GET range query should be structed as follows:
       curl -XGET http://localhost:8000/streams/Id/data/_search\?timestampFrom\=timestampFromValue&timestampTo\=timestampToValue    --   for range query
or  
      curl -XGET http://localhost:8000/streams/Id/data/_search\?timestampFrom\=timestampFromValue   --   for lower bounded only range query

It will be added in the wiki soon.

**Comment by konstantino** [comment]
thanks. Please include it in the wiki at some point in time.
