### ISSUE TITLE
timestamped datapoints

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#215]
it seems that it is impossible to push timestamped datapoints when creating a new data point. Is that done intentionally? The feature is needed in order to recreate historical information. The problem can be recreated by using a command such as this one: curl -XPOST -H  "Content-type: application/json" -d '{"timestamp": "2013-11-28T10:00:13.000", "value":"2"}' http://localhost:8000/streams/NIkSsVLHRIO5f4318t781A/data

**Comment by iakovosk** [comment]
Well, I tried it and it works for me. Can you please retry? What error did you get?

**Comment by konstantino** [comment]
Maybe I'm still running on an older version but here's the error I received: 

<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,
    {error,
        {badmatch,{error,econnrefused}},
        [{datapoints,process_post,2,[{file,"src/datapoints.erl"},{line,113}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,486}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]},
         {webmachine_mochiweb,loop,2,
             [{file,"src/webmachine_mochiweb.erl"},{line,74}]},
         {mochiweb_http,parse_headers,5,
             [{file,"src/mochiweb_http.erl"},{line,180}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></html>root@iot:/opt/sensor-cloud/src# Connection to localhost closed by remote host.

**Comment by andreasmh** [comment]
Can you post datapoints without the timestamp? I believe that you might not have the rabbit mq server running.  It says it crashes on line 113 in datapoints.erl, for me that is when it is trying to create an amqp connection to the rabbit server...

**Comment by iakovosk** [comment]
Also, in older versions of the system some features will not work if you store the value in quotes, because it is then considered a string. (However, it is unlikely that you encounter such a problem)

**Comment by konstantino** [comment]
issue is closed - I was using an older version - issue does not occur with the latest one!
