### ISSUE TITLE
predictions api

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#246]
Hi,

It seems like the predictions API is triggered via the website i.e HTTP GET request to 
http://localhost:3000/streams/s57H_d_qRSOafG18s5zb2A/predict?in=100&out=50&commit=Fetch+Prediction . Is there perhaps a more direct way to reach this function via the engine to avoid sending unnecessary traffic to the website?

**Comment by nikokon** [comment]
the prediction call to the api is
API-URL:API-Port/streams/#{stream_id}/_analyse?nr_values=#{nr_inputs}&nr_preds=#{nr_outputs}

**Comment by nikokon** [comment]
hmm... I'm not sure if it's visible but it should be UNDERSCOREanalyse?...

**Comment by nikokon** [comment]
the same for nrvalues.. should be nrUNDERSCOREvalues . It seems github uses the underscore as some text formatting

**Comment by konstantino** [comment]
thanks. Underscore prompts github to render the text in italics.
