### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by nikokon** [projectcs13/sensor-cloud#83]
Here are some issues regarding the API I think we should look over to get consistency.
Making these changes will also require to update the front-end and the API-documentation.

All GET/POST/PUT/DELETE should return in the same consistent manner for all resources.

Proposal: 
GET-requests
for USERS, STREAMS, RESOURCES etc should return in the same manner. 
a request to
USERS/{user_id} will return the json-object containing the USER with id: "user_id"
a request to 
USERS/ will return a json-object with the pattern {"users": [<list of users>]}
the same goes for STREAMS and RESOURCES.
STREAMS/{stream_id} will return a json-object containing the stream
RESOURCES/{resource_id} will return a json-object containing the resource
STREAMS/ will return the json-object {"streams": [<list of streams]}
RESOURCES/ will return the json-object {"resources": [<list of resources]}

If the resource is not found, the reply should also be consistent. Either a 404 on both kinds of request? or a 404 if a specific object is not found and the json-object {resource_type: []} where resource_type is user, stream or resource of no resources of that type was found.

**Comment by tosa7943** [comment]
I think this could be fixed quite fast in the back-end at least but the tests would need to be changed, no idea about the front-end and i think that the second version would be better, i.e. the empty list. Should PUT and DELETE perform in the same manner, i.e. give a 404 if the specified object does no exist, i assume that it would be the case.

**Comment by nikokon** [comment]
yes, I assume so! The important past is consistency...

**Comment by nikokon** [comment]
also.. A POST should return at least the ID of the newly created resource. Not exactly sure of the anatomy of the response but a 200 and the resource ID if the post is succesful?

**Comment by nikokon** [comment]
or perhaps a 201 created...
