### ISSUE TITLE
API changes [parameters]

### ISSUE THREAD

**Issue by nikokon** [projectcs13/sensor-cloud#84]
Whenever you do a get-request and expect a list of objects back (or rather an object with a list, see issue #83 ) you should be able to specify how many object you wish to retreive. 

Proposal:
improve API so a user can add ?tail=n to a get-request and receive n object back.

**Comment by andreasmh** [comment]
Jose is working on the size parameter in the search. When that is done it should be easy to just copy the same solution for get requests. 

It would probably be ?size=n and/or ?size=x&from=y

**Comment by nikokon** [comment]
This should be introduced to all recources, see issue #83
