### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by andreasmh** [projectcs13/sensor-cloud#91]
Right now, erlastic_search will return one of these if it gets an error:

```
    Status == 404 ->
        {error, not_found};
    Status == 409 ->
         {error, conflict};
    Status == 412 ->
         {error, precondition_failed};
    Status >= 400 ->
         {error, {Status, Body}};
```

The three top cases are handled in our system, but not the last more general one. We should add handling for the {error, {Status, Body}} case.

**Comment by nikokon** [comment]
This has been removed and we now instead only handle the general case. There might still exist calls in the code relying on these returns. This will have to be fixed

**Comment by andreasmh** [comment]
Fixed by changing the error handling in commit pull request #116
