### ISSUE TITLE
Timestamp consistency

### ISSUE THREAD

**Issue by gabrieltholsgard** [projectcs13/sensor-cloud#95]
I've noticed that we have different timestamps in the datapoints at different places, let's make it uniform!
Elastic Search stores it this way:
YYYYMMDDTHHMMSS.mmm

An example would be: "20131106T165043.000"

So when you get a datapoint assume a string in this format, and when creating a datapoint, make a timestamp string in this format.

**Comment by nikokon** [comment]
Tomas was talking about elastic search actually storing it as YYYYMMDDTHHMMSS.mmmz
an extra digit for timezone... I agree, we must keep it consistent

**Comment by tosa7943** [comment]
Yeah that was how it looked in elastic search data type thing, but i could not find any example of how it should look and when i tried to add it with that format it complained, so it might need to be changed so that it is a correct date-time type according to elastic search

**Comment by gabrieltholsgard** [comment]
So I think everyone all ready knows the format of the new timestamp, but just to make sure this is how it should look like:
"2013-11-26T17:16:21.000"

There is a macro I've done in pub_sub.hrl that is called TIME_NOW(Time) that basically should be called:
?TIME_NOW(erlang:localtime())
It will produce a timestamp of the right format and also includes miliseconds.. use it if you want.. and if suggested maybe move it to a more common place.

**Comment by andreasmh** [comment]
This has been fixed. So I will close this.
