### ISSUE TITLE
500 on /users HTTP GET request

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#96]
A 500 error is generated when making an HTTP GET request in a fresh installation where there are no users in the system. I guess the proper error message here would be an empty list.

{error,
    {error,function_clause,
        [{lib_json,encode,[not_found],[{file,"src/lib_json.erl"},{line,140}]},
         {users,get_user,2,[{file,"src/users.erl"},{line,157}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,558}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]},
         {webmachine_mochiweb,loop,2,
             [{file,"src/webmachine_mochiweb.erl"},{line,74}]}]}}

**Comment by tosa7943** [comment]
Yes, that is a problem that is caused by that there is no index in elastic search when you start a fresh install, we should make a task to try and fix this problem

**Comment by andreasmh** [comment]
Actually I think it is an issue with the error code being handled incorrectly. This issue has been fixed very recently, try "git pull origin develop".

**Comment by tosa7943** [comment]
Okey, but it should return the {'"hits":[]} and not an error in this case, i.e. listing all the users when no users exist

**Comment by andreasmh** [comment]
Well that depends if he is searching for a single user or a list of users. If he is trying to GET one user using the id then it should return {"error":"not_found"}, if he is searching for a collection of users it should return {'"hits":[]} or {'"users":[]}

**Comment by nikokon** [comment]
it should probably return {"users": []} see issue #83

**Comment by konstantino** [comment]
funny enough, the issue occurs only on a clean version where no users have
ever been created in the system. if one user is created and then the user
is deleted, HTTP GET on users gives very accurately: {"hits":[]}

**Comment by steine** [comment]
Would you like a direct channel to us where you could submit bugs or is 
the latency between me getting the mail and distributing the task enough?

/A

**Comment by konstantino** [comment]
I think I should actually stick to the github channel when it comes to
bugs/issues - I think its easier for you guys instead of proxying
everything through you Anders. What do you think?

As far as new things to discuss, new features we can fall back to e-mail.

**Comment by steine** [comment]
That's a good solution :)
GitHub for bugs

and

Mail for feature requests.

About the 500 response, apparently it's about the index not being 
created. We'll continue to look at it but it's not very prioritized as 
it works as soon as you've done a POST.

/A

**Comment by konstantino** [comment]
I think its a small problem (the 500 response). The easiest solution would
be to have a simple command that generates one entry into the system via
the installation script. That entry could be for example a dummy user. The
entry can either stay in the system or it can be removed (again by the same
script) and this would ensure that the index is always initialized.

**Comment by nikokon** [comment]
This issue seems to be fixed...
